### ISSUE TITLE
Spike: All Movie Page Component: Find dataset

### ISSUE THREAD

**Issue by hopieyimmie** [hopieyimmie/CSC307-ScreenSquad#5]
This is a research task where you would need to look into potential databases for finding movies. Which API we need to check out, how to connect it with the backend, etc.

**Comment by nickambrose7** [comment]
There are a few options for the database:

The Movie Database (TMDb): TMDb is a popular source for movie and TV show data. They offer a free API that you can use to access their data.

-[ About TMDb](https://www.themoviedb.org/about)

- [API information](https://www.themoviedb.org/documentation/api) (The API is free)
According to Chat GPT:
Integrating TMDb into a web app with a React frontend and an Express backend should be straightforward. TMDb provides a well-documented API that supports various data formats including JSON, which makes it easy to integrate with modern web technologies.

React can make HTTP requests to the TMDb API to retrieve movie data and display it in the frontend. Express can be used to handle the API requests from the frontend, fetch data from TMDb, and return it in a suitable format to the client.

Overall, using TMDb for a movie rating web application should be a good choice and the integration with React and Express should be relatively easy.


IMDb Datasets: IMDb provides several datasets that you can use for your project. You can find them here: https://www.imdb.com/interfaces/.

- I personally don't like this option as much because the documentation doesn't look as good.
